#if !defined(AFX_CHARTGRIDNAVIGATOR_H__902E9660_C4D8_4BFB_9D1A_A1A40A08B008__INCLUDED_)
#define AFX_CHARTGRIDNAVIGATOR_H__902E9660_C4D8_4BFB_9D1A_A1A40A08B008__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartGridNavigator wrapper class

class CChartGridNavigator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartGridNavigator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa92b03a8, 0xd509, 0x4d2f, { 0xa9, 0x53, 0xb2, 0x6e, 0xd8, 0x49, 0x8a, 0xb0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetGrid(LPDISPATCH newValue);
	void SetGridLink(long nNewValue);
	void EnableButtons();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTGRIDNAVIGATOR_H__902E9660_C4D8_4BFB_9D1A_A1A40A08B008__INCLUDED_)
