#if !defined(AFX_TEELISTBOX_H__D4B703F8_2C35_469C_99AE_0ED295665C63__INCLUDED_)
#define AFX_TEELISTBOX_H__D4B703F8_2C35_469C_99AE_0ED295665C63__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeListBox wrapper class

class CTeeListBox : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeListBox)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb6c1052d, 0xfb89, 0x11d4, { 0x93, 0xc9, 0x0, 0x60, 0x8, 0xa7, 0xee, 0xd4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	void UpdateSeries();
	long GetSelectedSeries();
	void SetSelectedSeries(long nNewValue);
	BOOL GetShowActive();
	void SetShowActive(BOOL bNewValue);
	BOOL GetShowColor();
	void SetShowColor(BOOL bNewValue);
	BOOL GetShowTitle();
	void SetShowTitle(BOOL bNewValue);
	BOOL GetShowIcon();
	void SetShowIcon(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEELISTBOX_H__D4B703F8_2C35_469C_99AE_0ED295665C63__INCLUDED_)
