#if !defined(AFX_TEEEDITOR_H__C6941047_A729_4892_983A_CBC325A337F3__INCLUDED_)
#define AFX_TEEEDITOR_H__C6941047_A729_4892_983A_CBC325A337F3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeEditorShowPages;
class CTeeEditorOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeeEditor wrapper class

class CTeeEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb6c10530, 0xfb89, 0x11d4, { 0x93, 0xc9, 0x0, 0x60, 0x8, 0xa7, 0xee, 0xd4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	CString GetEditorTitle();
	void SetEditorTitle(LPCTSTR lpszNewValue);
	long GetDefaultPage();
	void SetDefaultPage(long nNewValue);
	void ShowEditor();
	BOOL GetAutoRepaint();
	void SetAutoRepaint(BOOL bNewValue);
	CTeeEditorShowPages GetShowPages();
	long GetEditorLink();
	CTeeEditorOptions GetOptions();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEEDITOR_H__C6941047_A729_4892_983A_CBC325A337F3__INCLUDED_)
