#if !defined(AFX_GIFEXPORT_H__24F0E6CA_A6BE_46CF_88D6_6631152A60E4__INCLUDED_)
#define AFX_GIFEXPORT_H__24F0E6CA_A6BE_46CF_88D6_6631152A60E4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGIFExport wrapper class

class CGIFExport : public COleDispatchDriver
{
public:
	CGIFExport() {}		// Calls COleDispatchDriver default constructor
	CGIFExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGIFExport(const CGIFExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	long GetCompression();
	void SetCompression(long nNewValue);
	long GetDitherMode();
	void SetDitherMode(long nNewValue);
	long GetColorReduction();
	void SetColorReduction(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GIFEXPORT_H__24F0E6CA_A6BE_46CF_88D6_6631152A60E4__INCLUDED_)
