#if !defined(AFX_CHARTEDITORPANEL_H__4F222B1F_B786_11D5_94F9_006008A7EED4__INCLUDED_)
#define AFX_CHARTEDITORPANEL_H__4F222B1F_B786_11D5_94F9_006008A7EED4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartEditorPanel wrapper class

class CChartEditorPanel : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartEditorPanel)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2c37b0ad, 0xff7, 0x4e18, { 0xbf, 0x8a, 0xb4, 0x34, 0x69, 0xa2, 0xc4, 0x14 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void SelectUnderMouse();
	long GetBevelOuter();
	void SetBevelOuter(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTEDITORPANEL_H__4F222B1F_B786_11D5_94F9_006008A7EED4__INCLUDED_)
