#if !defined(AFX_CHARTGRID_H__CC066899_1A93_4238_B4FA_C5DEDCAE875C__INCLUDED_)
#define AFX_CHARTGRID_H__CC066899_1A93_4238_B4FA_C5DEDCAE875C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartGridCols;
class CChartGridRows;

/////////////////////////////////////////////////////////////////////////////
// CChartGrid wrapper class

class CChartGrid : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartGrid)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xf069c83a, 0x876f, 0x4c9d, { 0xb5, 0x40, 0xd7, 0x61, 0x42, 0x86, 0x6, 0xdb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	long GetCol();
	void SetCol(long nNewValue);
	long GetColCount();
	BOOL GetEditorMode();
	void SetEditorMode(BOOL bNewValue);
	long GetGridHeight();
	long GetGridWidth();
	long GetLeftCol();
	void SetLeftCol(long nNewValue);
	long GetGridLink();
	void RecalcDimensions();
	BOOL GetShowLabels();
	void SetShowLabels(BOOL bNewValue);
	BOOL GetShowColors();
	void SetShowColors(BOOL bNewValue);
	BOOL GetShowFields();
	void SetShowFields(BOOL bNewValue);
	CChartGridCols Cols();
	CChartGridRows Rows();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTGRID_H__CC066899_1A93_4238_B4FA_C5DEDCAE875C__INCLUDED_)
