#if !defined(AFX_CHARTPAGENAVIGATOR_H__2D681A3A_8E4C_4A6D_BF3A_D1650030EFFE__INCLUDED_)
#define AFX_CHARTPAGENAVIGATOR_H__2D681A3A_8E4C_4A6D_BF3A_D1650030EFFE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartPageNavigator wrapper class

class CChartPageNavigator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartPageNavigator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc4bb55c5, 0x9f2c, 0x4b46, { 0x86, 0xf3, 0xf3, 0xbb, 0x52, 0xa8, 0x3b, 0x4e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void EnableButtons();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTPAGENAVIGATOR_H__2D681A3A_8E4C_4A6D_BF3A_D1650030EFFE__INCLUDED_)
