#if !defined(AFX_SERIESTEXTSOURCE_H__41D19E98_1DCF_4FF1_9694_508D20C5B676__INCLUDED_)
#define AFX_SERIESTEXTSOURCE_H__41D19E98_1DCF_4FF1_9694_508D20C5B676__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeriesTextFields;
class CSeriesTextField;

/////////////////////////////////////////////////////////////////////////////
// CSeriesTextSource wrapper class

class CSeriesTextSource : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSeriesTextSource)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4061f8f2, 0x1d1c, 0x11d5, { 0x94, 0x1, 0x0, 0x60, 0x8, 0xa7, 0xee, 0xd4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void Close();
	void Load();
	void LoadAsStream(const VARIANT& AStream);
	void LoadFromFile(LPCTSTR FileName);
	void LoadFromURL(LPCTSTR URL);
	void Open();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	long GetHeaderLines();
	void SetHeaderLines(long nNewValue);
	CSeriesTextFields GetFields();
	CString GetFieldSeparator();
	void SetFieldSeparator(LPCTSTR lpszNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	CSeriesTextField AddField(LPCTSTR AName, long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SERIESTEXTSOURCE_H__41D19E98_1DCF_4FF1_9694_508D20C5B676__INCLUDED_)
