#if !defined(AFX_TEECOMMANDER_H__BFEAE2C7_FA43_42ED_8ADA_D11EDBADCE9C__INCLUDED_)
#define AFX_TEECOMMANDER_H__BFEAE2C7_FA43_42ED_8ADA_D11EDBADCE9C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeCommander wrapper class

class CTeeCommander : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeCommander)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb6c10532, 0xfb89, 0x11d4, { 0x93, 0xc9, 0x0, 0x60, 0x8, 0xa7, 0xee, 0xd4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	BOOL GetLabelValues();
	void SetLabelValues(BOOL bNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void SetEditor(LPDISPATCH newValue);
	void SetPreviewer(LPDISPATCH newValue);
	void SetEditorLink(long nNewValue);
	void SetPreviewerLink(long nNewValue);
	BOOL GetVertical();
	void SetVertical(BOOL bNewValue);
	VARIANT GetControls();
	void SetControls(const VARIANT& newValue);
	VARIANT GetButtons();
	void SetButtons(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEECOMMANDER_H__BFEAE2C7_FA43_42ED_8ADA_D11EDBADCE9C__INCLUDED_)
